# -*- coding: utf-8 -*-
"""Refined_FilterDivision_L1+L2_Without_TF_Final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eHMR75MlfTsrrFVYOL1IWEbThcoe9nJd
"""

import numpy as np 
import pandas as pd 
import scipy
import scipy.signal
import sys
import time
from datetime import datetime
np.set_printoptions(threshold=sys.maxsize)
np.set_printoptions(precision=1000, suppress=None)

def ArrayFromText (myfile):
  fileString = myfile.read()
  fileString = fileString.replace("[", " ")
  fileString = fileString.replace("]", " ")
  fileString = fileString.replace("\n", " ")
  arrayfromText = (np.fromstring(fileString , sep=' '))
  return arrayfromText

def readfromfile(filename):
  myfile = open(filename)
  fileString = myfile.read()
  fileString = fileString.replace("[", " ")
  fileString = fileString.replace("]", " ")
  fileString = fileString.replace("\n", " ")
  inputarray = (np.fromstring(fileString , sep=' ')) 
  return inputarray

start_time = datetime.now()
  
myfile = open("/content/1convBias.txt")
arrayfromTextCONVBIAS1 = ArrayFromText (myfile)

myfile = open("/content/1convWeights.txt")
A= ArrayFromText (myfile)
arrayfromTextCONVWeight1  = A.reshape([4,5,5])

myfile = open("/content/2convBias.txt")
arrayfromTextCONVBias2 = ArrayFromText (myfile)

myfile = open("/content/2convWeights.txt")
A= ArrayFromText (myfile)
arrayfromTextCONVWeight2 = A.reshape([4,4,3,3])
MOVEDONE = np.moveaxis(arrayfromTextCONVWeight2,[0,1],[1,0])


myfile = open("/content/31densebias.txt")
arrayfromTextdensebias1 = ArrayFromText (myfile)

myfile = open("/content/31denseweights.txt")
arrayfromTextdenseweight1 = ArrayFromText (myfile)

myfile = open("/content/42densebias.txt")
arrayfromTextdensebias2 = ArrayFromText (myfile)

myfile = open("/content/42denseweights.txt")
arrayfromTextdenseweight2 = ArrayFromText (myfile)

end_time = datetime.now()
print('Duration of weights & bias : {}'.format(end_time - start_time))


start_time = datetime.now()

myfile = open("/content/input7.txt")
A= ArrayFromText (myfile)
Input_0 = A.reshape([28,28])
end_time = datetime.now()
print('Duration of the image : {}'.format(end_time - start_time))


def Conv1Layer_Without_TF (inputArray, ConvWeightsArray, ConvBiasArray):
  CONVWeight1movedold = [ConvWeightsArray]
  CONVWeight1moved = np.moveaxis(CONVWeight1movedold, [0,1,2,3],[2,3,0,1])
  convOpnew=  conv_2d_4d_layer1(inputArray,CONVWeight1moved )
  convOpnew[:,0:1,:,:] = convOpnew[:,0:1,:,:] + ConvBiasArray[0]
  convOpnew[:,1:2,:,:] = convOpnew[:,1:2,:,:] + ConvBiasArray[1]
  convOpnew[:,2:3,:,:] = convOpnew[:,2:3,:,:] + ConvBiasArray[2]
  convOpnew[:,3:4,:,:] = convOpnew[:,3:4,:,:] + ConvBiasArray[3]
  convOpnew[convOpnew < 0.0] = 0
  return convOpnew

def Conv1Layer_Without_TF_3 (inputArray, ConvWeightsArray, ConvBiasArray):
  CONVWeight1movedold = [ConvWeightsArray]
  CONVWeight1moved = np.moveaxis(CONVWeight1movedold, [0,1,2,3],[2,3,0,1])
  convOpnew=  conv_2d_4d_layer1_3(inputArray,CONVWeight1moved )
  convOpnew[:,0:1,:,:] = convOpnew[:,0:1,:,:] + ConvBiasArray[0]
  convOpnew[:,1:2,:,:] = convOpnew[:,1:2,:,:] + ConvBiasArray[1]
  convOpnew[:,2:3,:,:] = convOpnew[:,2:3,:,:] + ConvBiasArray[2]
  convOpnew[convOpnew < 0.0] = 0
  return convOpnew


def Conv1Layer_Without_TF_1 (inputArray, ConvWeightsArray, ConvBiasArray):
  CONVWeight1movedold = [ConvWeightsArray]
  CONVWeight1moved = np.moveaxis(CONVWeight1movedold, [0,1,2,3],[2,3,0,1])
  convOpnew=  conv_2d_4d_layer1_1(inputArray,CONVWeight1moved )
  convOpnew[:,0:1,:,:] = convOpnew[:,0:1,:,:] + ConvBiasArray[0]
  convOpnew[convOpnew < 0.0] = 0
  return convOpnew

#####
def conv_2d_4d_layer1(inputarray_2d,CONVWeight1moved ):
  filter1= CONVWeight1moved[:,:,:,0:1]
  filter1_2d= np.reshape(filter1, [5,5])
  filter2= CONVWeight1moved[:,:,:,1:2]
  filter2_2d= filter2.reshape([5,5])
  filter3= CONVWeight1moved[:,:,:,2:3]
  filter3_2d= filter3.reshape([5,5])
  filter4= CONVWeight1moved[:,:,:,3:4]
  filter4_2d= filter4.reshape([5,5])
  filter1_2d = np.flipud(np.fliplr(filter1_2d))
  filter2_2d = np.flipud(np.fliplr(filter2_2d))
  filter3_2d = np.flipud(np.fliplr(filter3_2d))
  filter4_2d = np.flipud(np.fliplr(filter4_2d))
  out1_2d = scipy.signal.convolve2d(inputarray_2d , filter1_2d , 'valid')
  out2_2d = scipy.signal.convolve2d(inputarray_2d , filter2_2d , 'valid')
  out3_2d = scipy.signal.convolve2d(inputarray_2d , filter3_2d , 'valid')
  out4_2d = scipy.signal.convolve2d(inputarray_2d , filter4_2d , 'valid')
  out3d = [out1_2d, out2_2d, out3_2d, out4_2d]
  out4d = np.array([out3d])
  return out4d


def conv_2d_4d_layer1_3(inputarray_2d,CONVWeight1moved ):
  filter1= CONVWeight1moved[:,:,:,0:1]
  filter1_2d= np.reshape(filter1, [5,5])
  filter2= CONVWeight1moved[:,:,:,1:2]
  filter2_2d= filter2.reshape([5,5])
  filter3= CONVWeight1moved[:,:,:,2:3]
  filter3_2d= filter3.reshape([5,5])
  filter1_2d = np.flipud(np.fliplr(filter1_2d))
  filter2_2d = np.flipud(np.fliplr(filter2_2d))
  filter3_2d = np.flipud(np.fliplr(filter3_2d))
  out1_2d = scipy.signal.convolve2d(inputarray_2d , filter1_2d , 'valid')
  out2_2d = scipy.signal.convolve2d(inputarray_2d , filter2_2d , 'valid')
  out3_2d = scipy.signal.convolve2d(inputarray_2d , filter3_2d , 'valid')
  out3d = [out1_2d, out2_2d, out3_2d]
  out4d = np.array([out3d])
  return out4d


def conv_2d_4d_layer1_1(inputarray_2d,CONVWeight1moved ):
  filter1= CONVWeight1moved[:,:,:,0:1]
  filter1_2d= np.reshape(filter1, [5,5])
  filter1_2d = np.flipud(np.fliplr(filter1_2d))
  out1_2d = scipy.signal.convolve2d(inputarray_2d , filter1_2d , 'valid')
  out3d = [out1_2d]
  out4d = np.array([out3d])
  return out4d

def Maxpool_Without_TF (inputarray, Axis1x, Axis2y):
  x = inputarray[:,0:1,:,:].reshape([1,Axis1x,Axis2y,1])
  xx = x.reshape([Axis1x,Axis2y])
  m, n = xx.shape
  m1f1x = xx.reshape(m//2, 2, n//2, 2).max((1, 3))

  x = inputarray[:,1:2,:,:].reshape([1,Axis1x,Axis2y,1])
  xx = x.reshape([Axis1x,Axis2y])
  m1f2x = xx.reshape(m//2, 2, n//2, 2).max((1, 3))

  x = inputarray[:,2:3,:,:].reshape([1,Axis1x,Axis2y,1])
  xx = x.reshape([Axis1x,Axis2y])
  m1f3x = xx.reshape(m//2, 2, n//2, 2).max((1, 3))

  x = inputarray[:,3:4,:,:].reshape([1,Axis1x,Axis2y,1])
  xx = x.reshape([Axis1x,Axis2y])
  m1f4x = xx.reshape(m//2, 2, n//2, 2).max((1, 3))

  m1fx = np.array([m1f1x, m1f2x, m1f3x, m1f4x])
  return m1fx


def Maxpool_Without_TF_3 (inputarray, Axis1x, Axis2y):
  
  x = inputarray[:,0:1,:,:].reshape([1,Axis1x,Axis2y,1])
  xx = x.reshape([Axis1x,Axis2y])
  m, n = xx.shape
  m1f1x = xx.reshape(m//2, 2, n//2, 2).max((1, 3))

  x = inputarray[:,1:2,:,:].reshape([1,Axis1x,Axis2y,1])
  xx = x.reshape([Axis1x,Axis2y])
  m1f2x = xx.reshape(m//2, 2, n//2, 2).max((1, 3))

  x = inputarray[:,2:3,:,:].reshape([1,Axis1x,Axis2y,1])
  xx = x.reshape([Axis1x,Axis2y])
  m1f3x = xx.reshape(m//2, 2, n//2, 2).max((1, 3))

  m1fx = np.array([m1f1x, m1f2x, m1f3x])
  return m1fx

def Maxpool_Without_TF_1 (inputarray, Axis1x, Axis2y):
  
  x = inputarray[:,0:1,:,:].reshape([1,Axis1x,Axis2y,1])
  xx = x.reshape([Axis1x,Axis2y])
  m, n = xx.shape
  m1f1x = xx.reshape(m//2, 2, n//2, 2).max((1, 3))

  m1fx = np.array([m1f1x])
  return m1fx

def Conv2Layer_Without_TF(inputArray, ConvWeightsArray, ConvBiasArray, Axis1x, Axis2y):
  rearrangedinput = np.moveaxis(inputArray, [1,2,3],[3,1,2])
  rearrangedweights = np.moveaxis(ConvWeightsArray, [0,1,2,3],[2,3,0 ,1 ])

  #CHANNEL 1
  inputarray_2d = rearrangedinput[:,:,:,0:1]
  inputarray_2d_c1= np.reshape(inputarray_2d, [Axis1x, Axis2y]) 
  filter11= rearrangedweights[:,:,0:1,0:1]
  filter11_2d= filter11.reshape([3,3])
  filter12= rearrangedweights[:,:,0:1,1:2]
  filter12_2d= filter12.reshape([3,3])
  filter13= rearrangedweights[:,:,0:1,2:3]
  filter13_2d= filter13.reshape([3,3])
  filter14= rearrangedweights[:,:,0:1,3:4]
  filter14_2d= filter14.reshape([3,3])
  filter11_2d = np.flipud(np.fliplr(filter11_2d))
  filter12_2d = np.flipud(np.fliplr(filter12_2d))
  filter13_2d = np.flipud(np.fliplr(filter13_2d))
  filter14_2d = np.flipud(np.fliplr(filter14_2d))
  out11_2d = scipy.signal.convolve2d(inputarray_2d_c1 , filter11_2d , 'valid')
  out12_2d = scipy.signal.convolve2d(inputarray_2d_c1 , filter12_2d , 'valid')
  out13_2d = scipy.signal.convolve2d(inputarray_2d_c1 , filter13_2d , 'valid')
  out14_2d = scipy.signal.convolve2d(inputarray_2d_c1 , filter14_2d , 'valid')


  #CHANNEL 2
  inputarray_2d = rearrangedinput[:,:,:,1:2]
  inputarray_2d_c2= np.reshape(inputarray_2d, [Axis1x, Axis2y]) 
  filter21= rearrangedweights[:,:,1:2,0:1]
  filter21_2d= filter21.reshape([3,3])
  filter22= rearrangedweights[:,:,1:2,1:2]
  filter22_2d= filter22.reshape([3,3])
  filter23= rearrangedweights[:,:,1:2,2:3]
  filter23_2d= filter23.reshape([3,3])
  filter24= rearrangedweights[:,:,1:2,3:4]
  filter24_2d= filter24.reshape([3,3])
  filter21_2d = np.flipud(np.fliplr(filter21_2d))
  filter22_2d = np.flipud(np.fliplr(filter22_2d))
  filter23_2d = np.flipud(np.fliplr(filter23_2d))
  filter24_2d = np.flipud(np.fliplr(filter24_2d))
  out21_2d = scipy.signal.convolve2d(inputarray_2d_c2 , filter21_2d , 'valid')
  out22_2d = scipy.signal.convolve2d(inputarray_2d_c2 , filter22_2d , 'valid')
  out23_2d = scipy.signal.convolve2d(inputarray_2d_c2 , filter23_2d , 'valid')
  out24_2d = scipy.signal.convolve2d(inputarray_2d_c2 , filter24_2d , 'valid')



  #CHANNEL 3
  inputarray_2d = rearrangedinput[:,:,:,2:3]
  inputarray_2d_c3= np.reshape(inputarray_2d, [Axis1x, Axis2y]) 
  filter31= rearrangedweights[:,:,2:3,0:1]
  filter31_2d= filter31.reshape([3,3])
  filter32= rearrangedweights[:,:,2:3,1:2]
  filter32_2d= filter32.reshape([3,3])
  filter33= rearrangedweights[:,:,2:3,2:3]
  filter33_2d= filter33.reshape([3,3])
  filter34= rearrangedweights[:,:,2:3,3:4]
  filter34_2d= filter34.reshape([3,3])
  filter31_2d = np.flipud(np.fliplr(filter31_2d))
  filter32_2d = np.flipud(np.fliplr(filter32_2d))
  filter33_2d = np.flipud(np.fliplr(filter33_2d))
  filter34_2d = np.flipud(np.fliplr(filter34_2d))
  out31_2d = scipy.signal.convolve2d(inputarray_2d_c3 , filter31_2d , 'valid')
  out32_2d = scipy.signal.convolve2d(inputarray_2d_c3 , filter32_2d , 'valid')
  out33_2d = scipy.signal.convolve2d(inputarray_2d_c3 , filter33_2d , 'valid')
  out34_2d = scipy.signal.convolve2d(inputarray_2d_c3 , filter34_2d , 'valid')



  #CHANNEL 4
  inputarray_2d = rearrangedinput[:,:,:,3:4]
  inputarray_2d_c4= np.reshape(inputarray_2d, [Axis1x, Axis2y]) 
  filter41= rearrangedweights[:,:,3:4,0:1]
  filter41_2d= filter41.reshape([3,3])
  filter42= rearrangedweights[:,:,3:4,1:2]
  filter42_2d= filter42.reshape([3,3])
  filter43= rearrangedweights[:,:,3:4,2:3]
  filter43_2d= filter43.reshape([3,3])
  filter44= rearrangedweights[:,:,3:4,3:4]
  filter44_2d= filter44.reshape([3,3])
  filter41_2d = np.flipud(np.fliplr(filter41_2d))
  filter42_2d = np.flipud(np.fliplr(filter42_2d))
  filter43_2d = np.flipud(np.fliplr(filter43_2d))
  filter44_2d = np.flipud(np.fliplr(filter44_2d))
  out41_2d = scipy.signal.convolve2d(inputarray_2d_c4 , filter41_2d , 'valid')
  out42_2d = scipy.signal.convolve2d(inputarray_2d_c4 , filter42_2d , 'valid')
  out43_2d = scipy.signal.convolve2d(inputarray_2d_c4 , filter43_2d , 'valid')
  out44_2d = scipy.signal.convolve2d(inputarray_2d_c4 , filter44_2d , 'valid')


  f3_f1x = out11_2d + out21_2d + out31_2d + out41_2d
  f3_f2x = out12_2d + out22_2d + out32_2d + out42_2d 
  f3_f3x = out13_2d + out23_2d + out33_2d + out43_2d 
  f3_f4x = out14_2d + out24_2d + out34_2d + out44_2d  

  f3x = [f3_f1x, f3_f2x, f3_f3x, f3_f4x]
  f3x = np.moveaxis(f3x, 0, -1)
  f3x = np.array([f3x])

  arrayfromTextCONVBias2 = ConvBiasArray
  c2b1 = arrayfromTextCONVBias2[0]
  c2b2 = arrayfromTextCONVBias2[1]
  c2b3 = arrayfromTextCONVBias2[2]
  c2b4 = arrayfromTextCONVBias2[3]
  f3x[:,:,:,0:1] = f3x[:,:,:,0:1] + c2b1
  f3x[:,:,:,1:2] = f3x[:,:,:,1:2] + c2b2
  f3x[:,:,:,2:3] = f3x[:,:,:,2:3] + c2b3
  f3x[:,:,:,3:4] = f3x[:,:,:,3:4] + c2b4

  f3x[f3x < 0.0] = 0
  outputf3x = np.moveaxis(f3x, [3,1,2], [1,2,3])
  return outputf3x

def FlattenLayer(featureMap4 , Axis1x, Axis2y): #4, 25
  xxx = featureMap4.reshape([Axis1x, Axis2y])
  xxxxy = np.moveaxis(xxx, [0,1], [1,0])
  product = Axis1x * Axis2y
  featureMap4 = xxxxy.reshape([product])
  return featureMap4


def Dense1 (inputarray, ww, arrayfromTextdensebias1 ):
  mulOnly = np.dot(inputarray, ww)
  Outtttt = np.add(mulOnly,arrayfromTextdensebias1 )
  Outtttt[Outtttt < 0.0] = 0
  return Outtttt

def Dense2 (inputarray, ww, arrayfromTextdensebias2):
  mulOnly = np.dot(inputarray, ww)
  Outtttt = np.add(mulOnly,arrayfromTextdensebias2 )
  return Outtttt
  
def Answer(Outtttt):
  answer = np.argmax(Outtttt)
  return answer

def ImageDivision_FirstThreeFilters(Image):
  featureMap1 =  Conv1Layer_Without_TF_3 (Image, arrayfromTextCONVWeight1[0:3,:,:], arrayfromTextCONVBIAS1[0:3]  )
  featureMap2 = Maxpool_Without_TF_3 (featureMap1, 24, 24)
  return featureMap2

def ImageDivision_LastFilter(Image):
  featureMap1 =  Conv1Layer_Without_TF_1 (Image, arrayfromTextCONVWeight1[3:4,:,:], arrayfromTextCONVBIAS1[3:4]  )
  featureMap2 = Maxpool_Without_TF_1 (featureMap1, 24, 24)
  return featureMap2

def ImageDivision_FirstFourLayers(Image, a, b, c):
  featureMap1 =  Conv1Layer_Without_TF (Image, arrayfromTextCONVWeight1, arrayfromTextCONVBIAS1  )
  featureMap2 = Maxpool_Without_TF (featureMap1, 24, a)
  featureMap3= Conv2Layer_Without_TF([featureMap2.reshape([4, 12, b])], MOVEDONE , arrayfromTextCONVBias2, 12, b)
  featureMap4=  Maxpool_Without_TF(featureMap3, 10, c)
  return featureMap4

def FilterDivision_L1_L2_DividedNetwork(Image):
  start_time = datetime.now()
  Part1 = ImageDivision_FirstThreeFilters(Image)
  end_time = datetime.now()
  print('Part1 Duration (3 filters) : {}'.format(end_time - start_time))

  start_time = datetime.now()
  Part2 = ImageDivision_LastFilter(Image)
  end_time = datetime.now()
  print('Part2 Duration (last filter) : {}'.format(end_time - start_time))
  
  start_time = datetime.now()
  B4 =  np.array(np.concatenate((Part1 , Part2), axis=0))
  featureMap3= Conv2Layer_Without_TF([B4.reshape([4, 12, 12])], MOVEDONE , arrayfromTextCONVBias2, 12, 12)
  featureMap4=  Maxpool_Without_TF(featureMap3, 10, 10)
  featureMap4new = FlattenLayer(featureMap4 , 4, 25)
  featureMap5 = Dense1(featureMap4new, arrayfromTextdenseweight1.reshape([100,25]), arrayfromTextdensebias1)
  featureMap6 = Dense2(featureMap5, arrayfromTextdenseweight2.reshape([25,10]), arrayfromTextdensebias2)
  result =  Answer(featureMap6)
  end_time = datetime.now()
  print('Rest Duration : {}'.format(end_time - start_time))
  return result

def NormalNetwork(Image):
  NormalF4 = ImageDivision_FirstFourLayers(Image, 24, 12, 10)
  featureMap4new = FlattenLayer(NormalF4 , 4, 25)
  featureMap5 = Dense1(featureMap4new, arrayfromTextdenseweight1.reshape([100,25]), arrayfromTextdensebias1)
  featureMap6 = Dense2(featureMap5, arrayfromTextdenseweight2.reshape([25,10]), arrayfromTextdensebias2)
  result =  Answer(featureMap6)
  return result

start_time = datetime.now()
print("Normal Network", NormalNetwork(Input_0))
end_time = datetime.now()
print('Normal Network Duration: {}'.format(end_time - start_time))

start_time = datetime.now()
print("Divided Network", FilterDivision_L1_L2_DividedNetwork(Input_0))
end_time = datetime.now()
print('Divided Network Duration: {}'.format(end_time - start_time))